base_url = "https://liuyu.xin"
title = "liuyuxin"
description = "医学生，开发者"
author = "liuyuxin"
default_language = "zh"
theme = "serene"
output_dir = "public"
compile_sass = true
minify_html = false
build_search_index = false
generate_feeds = true
feed_filenames = ["feed.xml"]
taxonomies = [{ name = "tags" }, { name = "categories" }]
generate_sitemap = true
generate_robots_txt = true

[markdown]
highlight_code = true
highlight_theme = "css"
extra_syntaxes_and_themes = ["highlight_themes"]
highlight_themes_css = [
    { theme = "serene-light", filename = "hl-light.css" },
    { theme = "serene-dark", filename = "hl-dark.css" },
]
render_emoji = false
external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = false

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[extra]
sections = [
    # { name = "home", path = "/", is_external = false },
    { name = "posts", path = "/posts", is_external = false },
    { name = "tags", path = "/tags", is_external = false },
    { name = "projects", path = "/projects", is_external = false },
    { name = "resume", path = "/resume.pdf", is_external = true },
    { name = "rss", path = "/feed.xml", is_external = true },
]

blog_section_path = "/posts"

back_link_text = "Back" # Text of the back button
force_theme = false     # false | "light" | "dark"

footer_copyright = "© 2025 liuyuxin 京ICP备2022029058号"
footer_credits = false

not_found_error_text = "Not Found"
not_found_recover_text = "« back to home »"

reaction = false                                       # Whether to show anonymous reactions (Note: You need to set up a working api endpoint to enable anonymous reaction)
reaction_align = "right"                               # "left" | "center" | "right"
reaction_endpoint = "https://example.com/api/reaction"
