[[project]]
name = "MeRead"
desc = "简洁易用的 RSS 阅读器，使用 Flutter 开发，基于 Material You 设计"
tags = ["flutter", "android"]
img = ""
links = [
    { name = "Github", url = "https://github.com/gvenusleo/MeRead" },
    { name = "Download", url = "https://github.com/gvenusleo/MeRead/releases/latest" },
]

[[project]]
name = "lex-app"
desc = "桌面端跨平台划词翻译软件，使用 Flutter 开发，支持多种翻译和 AI 服务"
tags = ["flutter", "ai"]
img = ""
links = [
    { name = "Github", url = "https://github.com/gvenusleo/lex-app" },
    { name = "Download", url = "https://github.com/gvenusleo/lex-app/releases/latest" },
]
